name: passman
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^1.0.1
  connectivity_plus: ^1.0.0
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.0-beta.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_storage: ^8.0.0
  flutter:
    sdk: flutter
  flutter_tabler_icons: ^1.0.3-rc.1
  google_fonts: ^2.0.0
  google_sign_in: ^5.0.1
  hashids2: ^2.0.0
  image_picker: ^0.7.3
  logger: ^1.0.0
  lottie: ^1.0.1
  permission_handler: ^6.1.1
  provider: ^5.0.0
  qr_code_scanner: ^0.4.0-nullsafety.0
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/fonts/
  fonts:
    - family: Handwriting
      fonts:
        - asset: assets/fonts/Handwriting.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700