name: passman
description: Password Manager, Stores your all passwords. No one knows your
  passwords. Hide from everyone, sometimes from us and you.

version: 2.3.1-alpha

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^1.0.1
  connectivity_plus: ^1.0.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.0
  device_info_plus: ^1.0.0
  encrypt: ^5.0.0-beta.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_storage: ^8.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.1
  google_fonts: ^2.0.0
  google_sign_in: ^5.0.1
  image: ^3.0.2
  image_picker: ^0.7.3
  lottie: ^1.0.1
  network_to_file_image: ^3.0.0
  path_provider: ^2.0.1
  pedantic: ^1.11.0
  permission_handler: ^6.1.1
  provider: ^5.0.0
  qr_code_scanner: ^0.4.0-nullsafety.0
  qr_flutter: ^4.0.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/fonts/
  fonts:
    - family: IconsFont
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: QuickSand
      fonts:
        - asset: assets/fonts/Quicksand.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
